mergeInto(LibraryManager.library, {
  $EXA__deps: [],
  $EXA: {
    MSGTYPE: Object.freeze({
      UNDEFINED0 : 0,
      UNDEFINED1 : 1,
      UNDEFINED2 : 2,
      FORK : 3,
      EXIT_FROM_RESMGR : 4,
      SHOW_IFRAME : 5,
      HIDE_IFRAME : 6,
      SHOW_IFRAME_WAYLAND : 7,
      MOUSE_DOWN : 8,
      SEARCHING_IFRAME : 9,
      ASK_FOCUS : 10,
      UNDEFINED11 : 11,
      MINIMIZE : 12,
      MINIMIZE_ALL_DESKTOP : 13,
      MINIMIZE_ALL_DECO : 14,
    }),
    MSGID: Object.freeze({
      UNDEFINED0 : 0,
      REGISTER_DRIVER : 1,
      UNREGISTER_DRIVER : 2,
      REGISTER_DEVICE : 3,
      UNREGISTER_DEVICE : 4,
      MOUNT : 5,
      UMOUNT : 6,
      FORK : 7,
      EXECVE : 8,
      SOCKET : 9,
      BIND : 10,
      OPEN : 11,
      READ : 12,
      WRITE : 13,
      IOCTL : 14,
      CLOSE : 15,
      SETSID : 16,
      FCNTL : 17,
      GETSID : 18,
      DUP : 19,
      GETPPID : 20,
      GETPGID : 21,
      SETPGID : 22,
      PROBE_TTY : 23,
      READ_TTY : 24,
      WRITE_TTY : 25,
      IS_OPEN : 26,
      READLINK : 27,
      STAT : 28,
      FSTAT : 29,
      LSTAT : 30,
      SELECT : 31,
      SCTTY : 32,
      TIMERFD_CREATE : 33,
      GETCWD : 34,
      CHDIR : 35,
      GETDENTS : 36,
      WAIT : 37,
      EXIT : 38,
      SEEK : 39,
      SIGACTION : 40,
      SIGPROCMASK : 41,
      KILL : 42,
      SETITIMER : 43,
      GETITIMER : 44,
      EXA_RELEASE_SIGNAL : 45,
      FACCESSAT : 46,
      PIPE : 47,
      UNAME : 48,
      FSYNC : 49,
      UNLINKAT : 50,
      RENAMEAT : 51,
      SENDTO : 52,
      READ_SOCKET : 53,
      RECVFROM : 54,
      CONNECT : 55,
      GETSOCKNAME : 56,
      GETPEERNAME : 57,
      SOCKET_CLOSED : 58,
      SETSOCKOPT : 59,
      PTHREAD_CREATE : 60,
      PTHREAD_EXIT : 61,
      END_OF_SIGNAL : 62,
      TRUNCATE : 63,
      FTRUNCATE : 64,
      MKDIRAT : 65,
      RMDIR : 66,
      FSTATAT : 67,
    }),
  },
});
